package com.example.muhammadfaizankhan.geofencefirebase;

import com.firebase.client.Firebase;

import java.util.GregorianCalendar;
import java.util.HashMap;
import java.util.Map;

/**
 * Created by FAIZ on 4/29/15.
 */
/*
group-check-in-records : {
    groupID1 : {
        userID1 : {
            autoGeneratedTimestampBasedRecordID : {
                id: autoGeneratedTimestampBasedRecordID // from record
                subgroup-url: orgID1
                timestamp: timestamp,
                type: 1, // 1 = in, 2 = out
                source-type: 1, //1 = manual in web or mobile, 2 = automatic by geo-fencing in mobile, 3 =  automatic by beacon’s in mobile
                source-device-type : 1, // 1 = Web, 2 = iPhone, 3 = Android
                source-device-address: ip address or mobile number
                message: This is a test status message // optional
                location: {//not present in case of beacon based check in and out or the user does not select or allow data
                    lat : 24.8133877
                    lon : 67.0454256
                },
                identified-location-id : hehe867kd // from locations-defined, it will not be present if cannot identify the location i.e. “Other Location”,
                // it will always be present in beacon based automatic check in and out
            }
        }
    }
}
*/
public class MarkAttendanceFireBase {

    static int SOURCE_DEVICE_WEB = 1, SOURCE_DEVICE_IPHONE = 2, SOURCE_DEVICE_ANDROID = 3,
            SOURCE_TYPE_MANUAL = 1, SOURCE_TYPE_GEOFENCING = 2,
            TYPE_IN = 1, TYPE_OUT = 2;


    int mSourceDeviceType, //1 = Web, 2 = iPhone, 3 = Android
            mSourceType;    //1 = manual in web or mobile, 2 = automatic by geo-fencing in mobile,

    String mUser,//user name
            mGroupCheckinRecords = "https://test-employeeconnect.firebaseio.com/group-check-in-records",
            mGroupCheckinCurrent = "https://test-employeeconnect.firebaseio.com/group-check-in-current";

    public MarkAttendanceFireBase(String userName,
                                  int sourceDeviceType,
                                  int sourceType) {
        this.mSourceDeviceType = sourceDeviceType;
        this.mSourceType = sourceType;
        this.mUser = userName;
    }

    void markAttendance(String groupName,
                        String locationTitle,
                        String message,
                        int typeInOut,
                        double latitude,
                        double longitude) {

        Map<String, Object> map = new HashMap<String, Object>();
        map.put("identified-location-id", locationTitle);
        map.put("message", message);
        map.put("source-device-type", mSourceDeviceType);
        map.put("source-type", mSourceType);
        map.put("timestamp", new GregorianCalendar().getTimeInMillis());
        map.put("team-url", groupName);
        map.put("type", typeInOut);

        //making inner node
        Map<String, Object> location = new HashMap<String, Object>();
        location.put("lat", latitude);
        location.put("lon", longitude);

        map.put("location", location);

        Firebase groupCheckInRecordsRef = new Firebase(mGroupCheckinRecords);

        groupCheckInRecordsRef = groupCheckInRecordsRef.child(groupName).child(mUser).push();
        groupCheckInRecordsRef.setValue(map);

        map.put("id", groupCheckInRecordsRef.getKey());

        Firebase groupCheckinCurrentRef = new Firebase(mGroupCheckinCurrent);
        groupCheckinCurrentRef.child(groupName).child(mUser).setValue(map);

    }
}
